In [1]:
cd

/Users/hiralparmar

In [2]:
cd /Users/hiralparmar/Downloads

/Users/hiralparmar/Downloads

In [5]:
#import the required library
import numpy as np
import pandas as pd

#read csv file contain KL data
df_kl = pd.read_csv("KL_disrict.csv")
df_kl.head()

   Postcode  District                Area
0     52100    Kepong             Jinjang
1     52100    Kepong  Taman Bukit Maluri
2     51200  Segambut    Bandar Menjalara
3     51200  Segambut         Bukit Kiara
4     51200  Segambut         Bukit Tunku

In [6]:
#examine data
print('Kuala Lumpur dataframe has {} district and {} areas.'.format(
        len(df_kl['District'].unique()),
        df_kl.shape[0]
    )
)

#grouping data to find District with highest number of area
df_kl.groupby('District').count()

Kuala Lumpur dataframe has 11 district and 66 areas.

                  Postcode  Area
District
Bandar Tun Razak         6     6
Batu                     2     2
Bukit Bintang           11    11
Cheras                   9     9
Kepong                   2     2
Lembah Pantai            6     6
Segambut                11    11
Seputeh                  8     8
Setiawangsa              3     3
Titiwangsa               5     5
Wangsa Maju              3     3

In [7]:
#read and load JB data
df_jb = pd.read_csv("JB_disrict.csv")
df_jb.head()

   Postcode     District              Area
0     80000  Johor Bahru       Johor Bahru
1     81100  Johor Bahru  Bandar Dato' Onn
2     80200  Johor Bahru         Danga Bay
3     81100  Johor Bahru        Johor Jaya
4     81100  Johor Bahru         Desa Jaya

In [8]:
#examine
print('Johor Bahru dataframe has {} district and {} areas.'.format(
        len(df_jb['District'].unique()),
        df_jb.shape[0]
    )
)

#group by district
df_jb.groupby('District').count()

Johor Bahru dataframe has 3 district and 22 areas.

                 Postcode  Area
District
Iskandar Puteri         8     8
Johor Bahru            10    10
Pasir Gudang            4     4

In [ ]:
#now, using Geocoder and Google API, we get the Latitude and Longitude of each area
import geocoder
GOOGLE_API_KEY='AIzaSyAQWqMTOcyLBRDR2skO4F_5QEWzNDOlUHw'

#function to get latitude and longitude
def get_latlng(postal_code):
    lat_lng_coords = None
    while(lat_lng_coords is None):
        g = geocoder.google('{}, Malaysia'.format(postal_code), key=GOOGLE_API_KEY)
        lat_lng_coords = g.latlng
    return lat_lng_coords

#put new column of latitude and logitude into dataframe
postal_codes1 = df_kl['Area']    
coords = [ get_latlng(postal_code) for postal_code in postal_codes1.tolist() ]

df_kl_coords = pd.DataFrame(coords, columns=['Latitude', 'Longitude'])
df_kl['Latitude'] = df_kl_coords['Latitude']
df_kl['Longitude'] = df_kl_coords['Longitude']
df_kl.head(10)

In [ ]:
#new column for JB dataframe
postal_codes2 = df_jb['Area']    
coords = [ get_latlng(postal_code) for postal_code in postal_codes2.tolist() ]

df_jb_coords = pd.DataFrame(coords, columns=['Latitude', 'Longitude'])
df_jb['Latitude'] = df_jb_coords['Latitude']
df_jb['Longitude'] = df_jb_coords['Longitude']
df_jb.head(10)

In [ ]:
from geopy.geocoders import Nominatim
import folium

address = 'Kuala Lumpur, Malaysia'
geolocator = Nominatim()
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude

# create map of New York using latitude and longitude values
map_kl = folium.Map(location=[latitude, longitude], zoom_start=10)

# add markers to map
for lat, lng, borough, neighborhood in zip(df_kl['Latitude'], df_kl['Longitude'], df_kl['District'], df_kl['Area']):
    label = '{}, {}'.format(neighborhood, borough)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_kl)  
    
map_kl

In [ ]:
address = 'Johor Bahru, Malaysia'
geolocator = Nominatim()
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude

# create map of New York using latitude and longitude values
map_jb = folium.Map(location=[latitude, longitude], zoom_start=10)

# add markers to map
for lat, lng, borough, neighborhood in zip(df_jb['Latitude'], df_jb['Longitude'], df_jb['District'], df_jb['Area']):
    label = '{}, {}'.format(neighborhood, borough)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_jb)  
    
map_jb

In [ ]:
#slice the original dataframe and create a new dataframe of the Bukit Bintang
bbintang = df_kl[df_kl['District'] == 'Bukit Bintang'].reset_index(drop=True)

#get the geographical coordinates of Bukit Bintang, Kuala Lumpur
address = 'Bukit Bintang, Kuala Lumpur'
geolocator = Nominatim()
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude

# create map of Bukit Bintang using latitude and longitude values
map_bintang = folium.Map(location=[latitude, longitude], zoom_start=11)

# add markers to map
for lat, lng, label in zip(bbintang['Latitude'], bbintang['Longitude'], bbintang['Area']):
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_bintang)  
    
map_bintang

In [ ]:
#slice the original dataframe and create a new dataframe of the Iskandar
jdt = df_jb[df_jb['District'] == 'Johor Bahru'].reset_index(drop=True)

#get the geographical coordinates of Manhattan
address = 'Johor Bahru, Johor'
geolocator = Nominatim()
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude

# create map of Bukit Bintang using latitude and longitude values
map_jdt = folium.Map(location=[latitude, longitude], zoom_start=11)

# add markers to map
for lat, lng, label in zip(jdt['Latitude'], jdt['Longitude'], jdt['Area']):
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_jdt)  
    
map_jdt

In [ ]:
import requests # library to handle requests
from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe

#Define Foursquare Credentials and Version
CLIENT_ID = 'S34EAXF4QDSSZSRGKUHWA25K4ANQXEARFSR4ZI3W1EMBYZXW' # your Foursquare ID
CLIENT_SECRET = 'GV3ILPWKD2ETMZOLFMPRA0S3ORTYEQZAYMJA3RM2XN32OWVY' # your Foursquare Secret
VERSION = '20180604'

#explore the first neighborhood in our dataframe
#Get the neighborhood's latitude and longitude values.
neighborhood_latitude = bbintang.loc[0, 'Latitude'] # neighborhood latitude value
neighborhood_longitude = bbintang.loc[0, 'Longitude'] # neighborhood longitude value
neighborhood_name = bbintang.loc[0, 'Area'] # neighborhood name

#get the top 100 venues that are in Bukit Bintang within a radius of 500 meters
LIMIT = 100 # limit of number of venues returned by Foursquare API
radius = 500 # define radius
url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    VERSION, 
    neighborhood_latitude, 
    neighborhood_longitude, 
    radius, 
    LIMIT)

#Send the GET request and examine the resutls
results = requests.get(url).json()

#borrow the get_category_type function from the Foursquare lab.
# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

#clean the json and structure it into a pandas dataframe
venues = results['response']['groups'][0]['items']    
nearby_venues = json_normalize(venues) # flatten JSON

# filter columns
filtered_columns = ['venue.name', 'venue.categories', 'venue.location.lat', 'venue.location.lng']
nearby_venues =nearby_venues.loc[:, filtered_columns]

# filter the category for each row
nearby_venues['venue.categories'] = nearby_venues.apply(get_category_type, axis=1)

# clean columns
nearby_venues.columns = [col.split(".")[-1] for col in nearby_venues.columns]
print('{} venues were returned by Foursquare for Bukit Bintang, Kuala Lumpur.'.format(nearby_venues.shape[0]))
nearby_venues.head()

In [ ]:
#explore the first neighborhood in our dataframe
#Get the neighborhood's latitude and longitude values.
neighborhood_latitude = jdt.loc[0, 'Latitude'] # neighborhood latitude value
neighborhood_longitude = jdt.loc[0, 'Longitude'] # neighborhood longitude value
neighborhood_name = jdt.loc[0, 'Area'] # neighborhood name

#get the top 100 venues that are in Marble Hill within a radius of 500 meters
LIMIT = 100 # limit of number of venues returned by Foursquare API
radius = 500 # define radius
url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    VERSION, 
    neighborhood_latitude, 
    neighborhood_longitude, 
    radius, 
    LIMIT)

#Send the GET request and examine the resutls
results = requests.get(url).json()

#clean the json and structure it into a pandas dataframe
venues = results['response']['groups'][0]['items']    
nearby_venues = json_normalize(venues) # flatten JSON

# filter columns
filtered_columns = ['venue.name', 'venue.categories', 'venue.location.lat', 'venue.location.lng']
nearby_venues =nearby_venues.loc[:, filtered_columns]

# filter the category for each row
nearby_venues['venue.categories'] = nearby_venues.apply(get_category_type, axis=1)

# clean columns
nearby_venues.columns = [col.split(".")[-1] for col in nearby_venues.columns]
print('{} venues were returned by Foursquare for Johor Bahru.'.format(nearby_venues.shape[0]))
nearby_venues.head()

In [ ]:
#function to repeat the same process to all area
def getNearbyVenues(names, latitudes, longitudes, radius=500):
    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Area', 
                  'Area Latitude', 
                  'Area Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
     return(nearby_venues)

#run the above function on each neighborhood and create a new dataframe
bintang_venues = getNearbyVenues(names=bbintang['Area'],
                                   latitudes=bbintang['Latitude'],
                                   longitudes=bbintang['Longitude']
                                  )

#check the size of the resulting dataframe
print(bintang_venues.shape)
bintang_venues.head()

In [ ]:
#run the above function on each neighborhood and create a new dataframe
jdt_venues = getNearbyVenues(names=jdt['Area'],
                                   latitudes=jdt['Latitude'],
                                   longitudes=jdt['Longitude']
                                  )

#check the size of the resulting dataframe
print(jdt_venues.shape)
jdt_venues.head()

In [ ]:
#check how many venues were returned for each area
print('There are {} uniques categories in Kuala Lumpur.'.format(len(bintang_venues['Venue Category'].unique())))
bintang_venues.groupby('Area').count()

In [ ]:
#check how many venues were returned for each area
print('There are {} uniques categories in Johor bahru.'.format(len(jdt_venues['Venue Category'].unique())))
jdt_venues.groupby('Area').count()

In [ ]:
# one hot encoding
bintang_onehot = pd.get_dummies(bintang_venues[['Venue Category']], prefix="", prefix_sep="")

# add neighborhood column back to dataframe
bintang_onehot['Area'] = bintang_venues['Area'] 

# move neighborhood column to the first column
fixed_columns = [bintang_onehot.columns[-1]] + list(bintang_onehot.columns[:-1])
bintang_onehot = bintang_onehot[fixed_columns]

#examine the new dataframe size after one hot encoding
print('{} rows were returned after one hot encoding.'.format(bintang_onehot.shape[0]))

#group rows by neighborhood and by taking the mean of the frequency of occurrence of each category
bintang_grouped = bintang_onehot.groupby('Area').mean().reset_index()

#examine the new dataframe size after one hot encoding
print('{} rows were returned after grouping.'.format(bintang_grouped.shape[0]))

In [ ]:
#print each neighborhood along with the top 5 most common venues
num_top_venues = 5

for hood in bintang_grouped['Area']:
    print("----"+hood+"----")
    temp = bintang_grouped[bintang_grouped['Area'] == hood].T.reset_index()
    temp.columns = ['venue','freq']
    temp = temp.iloc[1:]
    temp['freq'] = temp['freq'].astype(float)
    temp = temp.round({'freq': 2})
    print(temp.sort_values('freq', ascending=False).reset_index(drop=True).head(num_top_venues))
    print('\n')

In [ ]:
#put into a pandas dataframe

#write a function to sort the venues in descending order
def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

#create the new dataframe and display the top 10 venues for each neighborhood
num_top_venues = 8

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['Area']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
areas_venues_sorted = pd.DataFrame(columns=columns)
areas_venues_sorted['Area'] = bintang_grouped['Area']

for ind in np.arange(bintang_grouped.shape[0]):
    areas_venues_sorted.iloc[ind, 1:] = return_most_common_venues(bintang_grouped.iloc[ind, :], num_top_venues)

areas_venues_sorted.head()

In [ ]:
from sklearn.cluster import KMeans

# set number of clusters
kclusters = 3

bintang_grouped_clustering = bintang_grouped.drop('Area', 1)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(bintang_grouped_clustering)

# check cluster labels generated for each row in the dataframe
kmeans.labels_[0:10] 

#create a new dataframe that includes the cluster as well as the top 10 venues for each neighborhood.
bintang_merged = bbintang

# add clustering labels
bintang_merged['Cluster Labels'] = kmeans.labels_

# merge toronto_grouped with toronto_data to add latitude/longitude for each neighborhood
bintang_merged = bintang_merged.join(areas_venues_sorted.set_index('Area'), on='Area')
bintang_merged.head()

In [ ]:
# Matplotlib and associated plotting modules
import matplotlib.cm as cm
import matplotlib.colors as colors

#Finally, let's visualize the resulting clusters
# create map 3.1343385, 101.6863371
bb_clusters = folium.Map(location=[3.1343385, 101.6863371], zoom_start=13)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i+x+(i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(bintang_merged['Latitude'], bintang_merged['Longitude'], bintang_merged['Area'], bintang_merged['Cluster Labels']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(bb_clusters)

In [ ]:
#put into a pandas dataframe

#write a function to sort the venues in descending order
def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

#create the new dataframe and display the top 10 venues for each neighborhood
num_top_venues = 8

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['Area']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
areas_venues_sorted = pd.DataFrame(columns=columns)
areas_venues_sorted['Area'] = bintang_grouped['Area']

for ind in np.arange(bintang_grouped.shape[0]):
    areas_venues_sorted.iloc[ind, 1:] = return_most_common_venues(bintang_grouped.iloc[ind, :], num_top_venues)

areas_venues_sorted.head()

In [ ]:
from sklearn.cluster import KMeans

# set number of clusters
kclusters = 3

bintang_grouped_clustering = bintang_grouped.drop('Area', 1)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(bintang_grouped_clustering)

# check cluster labels generated for each row in the dataframe
kmeans.labels_[0:10] 

#create a new dataframe that includes the cluster as well as the top 10 venues for each neighborhood.
bintang_merged = bbintang

# add clustering labels
bintang_merged['Cluster Labels'] = kmeans.labels_

# merge toronto_grouped with toronto_data to add latitude/longitude for each neighborhood
bintang_merged = bintang_merged.join(areas_venues_sorted.set_index('Area'), on='Area')

bintang_merged.head()

In [ ]:
# Matplotlib and associated plotting modules
import matplotlib.cm as cm
import matplotlib.colors as colors

#Finally, let's visualize the resulting clusters
# create map 3.1343385, 101.6863371
bb_clusters = folium.Map(location=[3.1343385, 101.6863371], zoom_start=13)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i+x+(i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(bintang_merged['Latitude'], bintang_merged['Longitude'], bintang_merged['Area'], bintang_merged['Cluster Labels']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(bb_clusters)
       
bb_clusters

In [ ]:
# set number of clusters
kclusters = 3

jdt_grouped_clustering = jdt_grouped.drop('Area', 1)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(jdt_grouped_clustering)

# check cluster labels generated for each row in the dataframe
kmeans.labels_[0:10] 

#create a new dataframe that includes the cluster as well as the top 10 venues for each neighborhood.
jdt_merged = jdt

# add clustering labels
jdt_merged['Cluster Labels'] = kmeans.labels_

# merge toronto_grouped with toronto_data to add latitude/longitude for each neighborhood
jdt_merged = jdt_merged.join(areas_venues_sorted.set_index('Area'), on='Area')

jdt_merged.head() # check the last columns!

In [ ]:
#Finally, let's visualize the resulting clusters
# create map
jdt_clusters = folium.Map(location=[latitude, longitude], zoom_start=11)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i+x+(i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(jdt_merged['Latitude'], jdt_merged['Longitude'], jdt_merged['Area'], jdt_merged['Cluster Labels']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(jdt_clusters)
       
jdt_clusters

In [ ]:
#Cluster 1 for Kuala Lumpur
bintang_merged.loc[bintang_merged['Cluster Labels'] == 0, bintang_merged.columns[[2] + list(range(5, bintang_merged.shape[1]))]]

In [ ]:
#Cluster 2 for Kuala Lumpur
bintang_merged.loc[bintang_merged['Cluster Labels'] == 1, bintang_merged.columns[[2] + list(range(5, bintang_merged.shape[1]))]]

In [ ]:
#Cluster 3 for Kuala Lumpur
bintang_merged.loc[bintang_merged['Cluster Labels'] == 2, bintang_merged.columns[[2] + list(range(5, bintang_merged.shape[1]))]]

In [ ]:
#Cluster 1 for Johor Bahru
jdt_merged.loc[jdt_merged['Cluster Labels'] == 0, jdt_merged.columns[[2] + list(range(5, jdt_merged.shape[1]))]]

In [ ]:
#Cluster 2 for Johor Bahru
jdt_merged.loc[jdt_merged['Cluster Labels'] == 1, jdt_merged.columns[[2] + list(range(5, jdt_merged.shape[1]))]]